name: Build and push Docker image
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: tailscale/tailscale
      - name: Generate image tags from repository
        id: tags
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail
          TAGS=(latest)
          TAGS+=($(git describe --tags --abbrev=0))
          TAGS+=($(git describe --tags))
          delim=""
          joined=""
          for tag in "${TAGS[@]}"; do
            joined="$joined$delim$tag"
            delim=","
          done
          echo "tags=$joined" | tee -a $GITHUB_OUTPUT
      - name: run build commands
        run: make publishdevtsidp REPO=ghcr.io/perchnet/tsidp TAGS=${{ steps.tags.outputs.tags }} PUSH=true
